//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFH_USZ_PICC.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BFH_USZ_PICC.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter PICC manually.
        /// </summary>
        public static string AddPICCPageAddPiccManualButtonText {
            get {
                return ResourceManager.GetString("AddPICCPageAddPiccManualButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a PICC.
        /// </summary>
        public static string AddPICCPagePICCEntryPlaceholderText {
            get {
                return ResourceManager.GetString("AddPICCPagePICCEntryPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PICC model could not be found.
        /// </summary>
        public static string AddPICCPagePICCNotFoundInformationText {
            get {
                return ResourceManager.GetString("AddPICCPagePICCNotFoundInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan barcode.
        /// </summary>
        public static string AddPICCPageScanButtonText {
            get {
                return ResourceManager.GetString("AddPICCPageScanButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PICC.
        /// </summary>
        public static string AddPICCPageTitleText {
            get {
                return ResourceManager.GetString("AddPICCPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string BasePageTitleText {
            get {
                return ResourceManager.GetString("BasePageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device can not call the USZ telemedicine. Contact 044 666 66 66.
        /// </summary>
        public static string CallUSZTelemedicineNotPossibleText {
            get {
                return ResourceManager.GetString("CallUSZTelemedicineNotPossibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to call USZ telemedicine?.
        /// </summary>
        public static string CallUSZTelemedicineText {
            get {
                return ResourceManager.GetString("CallUSZTelemedicineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call USZ telemedicine.
        /// </summary>
        public static string CallUSZTelemedizinButtonText {
            get {
                return ResourceManager.GetString("CallUSZTelemedizinButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string DisorderDetailPageActionLabelText {
            get {
                return ResourceManager.GetString("DisorderDetailPageActionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string DisorderDetailPageReasonLabelText {
            get {
                return ResourceManager.GetString("DisorderDetailPageReasonLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptom.
        /// </summary>
        public static string DisorderDetailPageSymptomLabelText {
            get {
                return ResourceManager.GetString("DisorderDetailPageSymptomLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disorder.
        /// </summary>
        public static string DisorderDetailPageTitleText {
            get {
                return ResourceManager.GetString("DisorderDetailPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue procedure steps.
        /// </summary>
        public static string DisorderPageIssueApproachTitleText {
            get {
                return ResourceManager.GetString("DisorderPageIssueApproachTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disorders.
        /// </summary>
        public static string DisorderPageTitleText {
            get {
                return ResourceManager.GetString("DisorderPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions.
        /// </summary>
        public static string EmergencyFlyoutAssistanceButtonText {
            get {
                return ResourceManager.GetString("EmergencyFlyoutAssistanceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions regarding your PICC, do not hesitate to contact the USZ hotline..
        /// </summary>
        public static string EmergencyFlyoutTelemedizinDescriptionText {
            get {
                return ResourceManager.GetString("EmergencyFlyoutTelemedizinDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approach in case of malfunction.
        /// </summary>
        public static string EmergencyFlyoutTitleText {
            get {
                return ResourceManager.GetString("EmergencyFlyoutTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string FailedText {
            get {
                return ResourceManager.GetString("FailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossary.
        /// </summary>
        public static string GlossaryPageTitleText {
            get {
                return ResourceManager.GetString("GlossaryPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InformationText {
            get {
                return ResourceManager.GetString("InformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home care.
        /// </summary>
        public static string JournalEntryInstitutionHomeCareText {
            get {
                return ResourceManager.GetString("JournalEntryInstitutionHomeCareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital.
        /// </summary>
        public static string JournalEntryInstitutionHospitalText {
            get {
                return ResourceManager.GetString("JournalEntryInstitutionHospitalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outpatient clinic.
        /// </summary>
        public static string JournalEntryInstitutionOutpatienClinicText {
            get {
                return ResourceManager.GetString("JournalEntryInstitutionOutpatienClinicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rehabilitation.
        /// </summary>
        public static string JournalEntryInstitutionRehabilitationText {
            get {
                return ResourceManager.GetString("JournalEntryInstitutionRehabilitationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified.
        /// </summary>
        public static string JournalEntryNotSpecifiedText {
            get {
                return ResourceManager.GetString("JournalEntryNotSpecifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string JournalEntryOthersText {
            get {
                return ResourceManager.GetString("JournalEntryOthersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affected person.
        /// </summary>
        public static string JournalEntryPersonAffectedPersonText {
            get {
                return ResourceManager.GetString("JournalEntryPersonAffectedPersonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family doctor.
        /// </summary>
        public static string JournalEntryPersonFamilyDoctorText {
            get {
                return ResourceManager.GetString("JournalEntryPersonFamilyDoctorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health expert staff.
        /// </summary>
        public static string JournalEntryPersonHealthExpertStaffText {
            get {
                return ResourceManager.GetString("JournalEntryPersonHealthExpertStaffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical technical assistant.
        /// </summary>
        public static string JournalEntryPersonMedicalTechnicalAssistantText {
            get {
                return ResourceManager.GetString("JournalEntryPersonMedicalTechnicalAssistantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nursing staff.
        /// </summary>
        public static string JournalEntryPersonNursingStaffText {
            get {
                return ResourceManager.GetString("JournalEntryPersonNursingStaffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        public static string JournalEntryPersonRelativeText {
            get {
                return ResourceManager.GetString("JournalEntryPersonRelativeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical specialist.
        /// </summary>
        public static string JournalEntryPersonSpecialistText {
            get {
                return ResourceManager.GetString("JournalEntryPersonSpecialistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XRay staff.
        /// </summary>
        public static string JournalEntryPersonXrayStaffText {
            get {
                return ResourceManager.GetString("JournalEntryPersonXrayStaffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administered drugs.
        /// </summary>
        public static string JournalOverviewPageAdministeredDrugEntry {
            get {
                return ResourceManager.GetString("JournalOverviewPageAdministeredDrugEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandage changing.
        /// </summary>
        public static string JournalOverviewPageBandagesChangingEntry {
            get {
                return ResourceManager.GetString("JournalOverviewPageBandagesChangingEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood withdrawal.
        /// </summary>
        public static string JournalOverviewPageBloodWithdrawalEntry {
            get {
                return ResourceManager.GetString("JournalOverviewPageBloodWithdrawalEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rinse the catheter.
        /// </summary>
        public static string JournalOverviewPageCatheterFlushEntry {
            get {
                return ResourceManager.GetString("JournalOverviewPageCatheterFlushEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administered infusions.
        /// </summary>
        public static string JournalOverviewPageInfusionEntry {
            get {
                return ResourceManager.GetString("JournalOverviewPageInfusionEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change MicroClave.
        /// </summary>
        public static string JournalOverviewPageMicroClaveChangingEntry {
            get {
                return ResourceManager.GetString("JournalOverviewPageMicroClaveChangingEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New entry.
        /// </summary>
        public static string JournalOverviewPageNewEntryButtonText {
            get {
                return ResourceManager.GetString("JournalOverviewPageNewEntryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What kind of entry would you like to add?.
        /// </summary>
        public static string JournalOverviewPageSelectANewNewEntryText {
            get {
                return ResourceManager.GetString("JournalOverviewPageSelectANewNewEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change StatLock.
        /// </summary>
        public static string JournalOverviewPageStatlockChangingEntry {
            get {
                return ResourceManager.GetString("JournalOverviewPageStatlockChangingEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string JournalOverviewPageTitleText {
            get {
                return ResourceManager.GetString("JournalOverviewPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string KnowledgeEntriesTitleText {
            get {
                return ResourceManager.GetString("KnowledgeEntriesTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to back up your personal data? You can adjust the information at any time in the settings. .
        /// </summary>
        public static string MasterDataBackUpQuestionText {
            get {
                return ResourceManager.GetString("MasterDataBackUpQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master data.
        /// </summary>
        public static string MasterDataText {
            get {
                return ResourceManager.GetString("MasterDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new PICC.
        /// </summary>
        public static string MyPICCPageAddNewPICCButtonText {
            get {
                return ResourceManager.GetString("MyPICCPageAddNewPICCButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current PICC.
        /// </summary>
        public static string MyPICCPageCurrentPICCText {
            get {
                return ResourceManager.GetString("MyPICCPageCurrentPICCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that you have not yet entered a PICC..
        /// </summary>
        public static string MyPICCPageNoPiccEnteredText {
            get {
                return ResourceManager.GetString("MyPICCPageNoPiccEnteredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous PICC.
        /// </summary>
        public static string MyPICCPagePreviousPICCText {
            get {
                return ResourceManager.GetString("MyPICCPagePreviousPICCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My PICC.
        /// </summary>
        public static string MyPICCPageTitleText {
            get {
                return ResourceManager.GetString("MyPICCPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoButtonText {
            get {
                return ResourceManager.GetString("NoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not any complications with your PICC to be expected. For your own safety, we still would like to inform you about possible problems..
        /// </summary>
        public static string PICCAssistanceDescriptionText {
            get {
                return ResourceManager.GetString("PICCAssistanceDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PICC.
        /// </summary>
        public static string PICCDetailPageAddNewPICCTitle {
            get {
                return ResourceManager.GetString("PICCDetailPageAddNewPICCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit PICC.
        /// </summary>
        public static string PICCDetailPageEditPICCTitle {
            get {
                return ResourceManager.GetString("PICCDetailPageEditPICCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an institution.
        /// </summary>
        public static string PICCDetailPageInsertCityPlaceholderText {
            get {
                return ResourceManager.GetString("PICCDetailPageInsertCityPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PICC body side:.
        /// </summary>
        public static string PICCDetailPagePICCBodysideText {
            get {
                return ResourceManager.GetString("PICCDetailPagePICCBodysideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size in french:.
        /// </summary>
        public static string PICCDetailPagePICCFrenchSizeText {
            get {
                return ResourceManager.GetString("PICCDetailPagePICCFrenchSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted on:.
        /// </summary>
        public static string PICCDetailPagePICCInsertedDateText {
            get {
                return ResourceManager.GetString("PICCDetailPagePICCInsertedDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string PICCDetailPagePICCInsertedPlaceText {
            get {
                return ResourceManager.GetString("PICCDetailPagePICCInsertedPlaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model name:.
        /// </summary>
        public static string PICCDetailPagePICCModelNameText {
            get {
                return ResourceManager.GetString("PICCDetailPagePICCModelNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PICC position:.
        /// </summary>
        public static string PICCDetailPagePICCPositionText {
            get {
                return ResourceManager.GetString("PICCDetailPagePICCPositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set PICC inactive.
        /// </summary>
        public static string PICCDetailPagePICCRemoveButtonText {
            get {
                return ResourceManager.GetString("PICCDetailPagePICCRemoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abroad.
        /// </summary>
        public static string PICCDetailPagePickerCountryAbroadText {
            get {
                return ResourceManager.GetString("PICCDetailPagePickerCountryAbroadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        public static string PICCDetailPagePickerCountrySwitzerlandText {
            get {
                return ResourceManager.GetString("PICCDetailPagePickerCountrySwitzerlandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not defined.
        /// </summary>
        public static string PICCDetailPagePickerNotDefinedText {
            get {
                return ResourceManager.GetString("PICCDetailPagePickerNotDefinedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above elbow.
        /// </summary>
        public static string PICCDetailPagePickerPositionAboveElbowText {
            get {
                return ResourceManager.GetString("PICCDetailPagePickerPositionAboveElbowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below elbow.
        /// </summary>
        public static string PICCDetailPagePickerPositionBelowElbowText {
            get {
                return ResourceManager.GetString("PICCDetailPagePickerPositionBelowElbowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string PICCDetailPagePickerSideLeftText {
            get {
                return ResourceManager.GetString("PICCDetailPagePickerSideLeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string PICCDetailPagePickerSideRightText {
            get {
                return ResourceManager.GetString("PICCDetailPagePickerSideRightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PICC.
        /// </summary>
        public static string PICCDetailPageTitleText {
            get {
                return ResourceManager.GetString("PICCDetailPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture detail.
        /// </summary>
        public static string PicturePageTitleText {
            get {
                return ResourceManager.GetString("PicturePageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add maintenance reminders.
        /// </summary>
        public static string SettingsPageAddReminderButtonText {
            get {
                return ResourceManager.GetString("SettingsPageAddReminderButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version.
        /// </summary>
        public static string SettingsPageAppVersionText {
            get {
                return ResourceManager.GetString("SettingsPageAppVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete all scheduled maintenance reminders?.
        /// </summary>
        public static string SettingsPageDelteScheduledRemindersText {
            get {
                return ResourceManager.GetString("SettingsPageDelteScheduledRemindersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After how many days will the memory be repeated?.
        /// </summary>
        public static string SettingsPageMaintenanceReminderFrequencyText {
            get {
                return ResourceManager.GetString("SettingsPageMaintenanceReminderFrequencyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PICC should be maintained.
        /// </summary>
        public static string SettingsPageMaintenanceReminderInformationText {
            get {
                return ResourceManager.GetString("SettingsPageMaintenanceReminderInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often should the memory be repeated?.
        /// </summary>
        public static string SettingsPageMaintenanceReminderRepetitionText {
            get {
                return ResourceManager.GetString("SettingsPageMaintenanceReminderRepetitionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set time for reminder.
        /// </summary>
        public static string SettingsPageMaintenanceReminderSetDailyTimeText {
            get {
                return ResourceManager.GetString("SettingsPageMaintenanceReminderSetDailyTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set start date.
        /// </summary>
        public static string SettingsPageMaintenanceReminderSetStartDateText {
            get {
                return ResourceManager.GetString("SettingsPageMaintenanceReminderSetStartDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance reminder.
        /// </summary>
        public static string SettingsPageMaintenanceReminderText {
            get {
                return ResourceManager.GetString("SettingsPageMaintenanceReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My personal data.
        /// </summary>
        public static string SettingsPagePersonalDataButtonText {
            get {
                return ResourceManager.GetString("SettingsPagePersonalDataButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitleText {
            get {
                return ResourceManager.GetString("SettingsPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate:.
        /// </summary>
        public static string UserMasterDataPageBirthdateLabelText {
            get {
                return ResourceManager.GetString("UserMasterDataPageBirthdateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delte my data.
        /// </summary>
        public static string UserMasterDataPageDeleteAllMasterDataButton {
            get {
                return ResourceManager.GetString("UserMasterDataPageDeleteAllMasterDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete all personal data?.
        /// </summary>
        public static string UserMasterDataPageDelteAllPersonalDataText {
            get {
                return ResourceManager.GetString("UserMasterDataPageDelteAllPersonalDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Mail:.
        /// </summary>
        public static string UserMasterDataPageEmailLabelText {
            get {
                return ResourceManager.GetString("UserMasterDataPageEmailLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellphone:.
        /// </summary>
        public static string UserMasterDataPageMobileLabelText {
            get {
                return ResourceManager.GetString("UserMasterDataPageMobileLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string UserMasterDataPageNameLabelText {
            get {
                return ResourceManager.GetString("UserMasterDataPageNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string UserMasterDataPagePhoneLabelText {
            get {
                return ResourceManager.GetString("UserMasterDataPagePhoneLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place:.
        /// </summary>
        public static string UserMasterDataPagePlaceLabelText {
            get {
                return ResourceManager.GetString("UserMasterDataPagePlaceLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salutation:.
        /// </summary>
        public static string UserMasterDataPageSalutationLabelText {
            get {
                return ResourceManager.GetString("UserMasterDataPageSalutationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street:.
        /// </summary>
        public static string UserMasterDataPageStreetLabelText {
            get {
                return ResourceManager.GetString("UserMasterDataPageStreetLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        public static string UserMasterDataPageSurnameLabelText {
            get {
                return ResourceManager.GetString("UserMasterDataPageSurnameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My personal data.
        /// </summary>
        public static string UserMasterDataPageTitleText {
            get {
                return ResourceManager.GetString("UserMasterDataPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP:.
        /// </summary>
        public static string UserMasterDataPageZIPLabelText {
            get {
                return ResourceManager.GetString("UserMasterDataPageZIPLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesButtonText {
            get {
                return ResourceManager.GetString("YesButtonText", resourceCulture);
            }
        }
    }
}
