//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFH_USZ_PICC.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BFH_USZ_PICC.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter PICC manually ähnelt.
        /// </summary>
        public static string AddPICCPageAddPiccManualButtonText {
            get {
                return ResourceManager.GetString("AddPICCPageAddPiccManualButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a PICC ähnelt.
        /// </summary>
        public static string AddPICCPagePICCEntryPlaceholderText {
            get {
                return ResourceManager.GetString("AddPICCPagePICCEntryPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan barcode ähnelt.
        /// </summary>
        public static string AddPICCPageScanButtonText {
            get {
                return ResourceManager.GetString("AddPICCPageScanButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add PICC ähnelt.
        /// </summary>
        public static string AddPICCPageTitleText {
            get {
                return ResourceManager.GetString("AddPICCPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page ähnelt.
        /// </summary>
        public static string BasePageTitleText {
            get {
                return ResourceManager.GetString("BasePageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action ähnelt.
        /// </summary>
        public static string DisorderDetailPageActionLabelText {
            get {
                return ResourceManager.GetString("DisorderDetailPageActionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Call USZ telemedicine ähnelt.
        /// </summary>
        public static string DisorderDetailPageCallUSZButtonText {
            get {
                return ResourceManager.GetString("DisorderDetailPageCallUSZButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reason ähnelt.
        /// </summary>
        public static string DisorderDetailPageReasonLabelText {
            get {
                return ResourceManager.GetString("DisorderDetailPageReasonLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Symptom ähnelt.
        /// </summary>
        public static string DisorderDetailPageSymptomLabelText {
            get {
                return ResourceManager.GetString("DisorderDetailPageSymptomLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disorder ähnelt.
        /// </summary>
        public static string DisorderDetailPageTitleText {
            get {
                return ResourceManager.GetString("DisorderDetailPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Usually there are no complications with your PICC expected. For safety reasons, we would like to show you possible signs of issues. ähnelt.
        /// </summary>
        public static string DisorderPageIssueApproachDescriptionText {
            get {
                return ResourceManager.GetString("DisorderPageIssueApproachDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Issue procedure steps ähnelt.
        /// </summary>
        public static string DisorderPageIssueApproachTitleText {
            get {
                return ResourceManager.GetString("DisorderPageIssueApproachTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disorders ähnelt.
        /// </summary>
        public static string DisorderPageTitleText {
            get {
                return ResourceManager.GetString("DisorderPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solutions ähnelt.
        /// </summary>
        public static string EmergencyFlyoutAssistanceButtonText {
            get {
                return ResourceManager.GetString("EmergencyFlyoutAssistanceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Call USZ Hotline ähnelt.
        /// </summary>
        public static string EmergencyFlyoutTelemedizinButtonText {
            get {
                return ResourceManager.GetString("EmergencyFlyoutTelemedizinButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you have any questions regarding your PICC, do not hesitate to contact the USZ hotline. ähnelt.
        /// </summary>
        public static string EmergencyFlyoutTelemedizinDescriptionText {
            get {
                return ResourceManager.GetString("EmergencyFlyoutTelemedizinDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Approach in case of malfunction ähnelt.
        /// </summary>
        public static string EmergencyFlyoutTitleText {
            get {
                return ResourceManager.GetString("EmergencyFlyoutTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are not any complications with your PICC to be expected. For your own safety, we still would like to inform you about possible problems. ähnelt.
        /// </summary>
        public static string EmergencyFyloutAssistanceDescriptionText {
            get {
                return ResourceManager.GetString("EmergencyFyloutAssistanceDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Glossary ähnelt.
        /// </summary>
        public static string GlossaryPageTitleText {
            get {
                return ResourceManager.GetString("GlossaryPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FAQ ähnelt.
        /// </summary>
        public static string KnowledgeEntriesTitleText {
            get {
                return ResourceManager.GetString("KnowledgeEntriesTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add a new PICC ähnelt.
        /// </summary>
        public static string MyPICCPageAddNewPICCButtonText {
            get {
                return ResourceManager.GetString("MyPICCPageAddNewPICCButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current PICC ähnelt.
        /// </summary>
        public static string MyPICCPageCurrentPICCText {
            get {
                return ResourceManager.GetString("MyPICCPageCurrentPICCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It seems that you have not yet entered a PICC. ähnelt.
        /// </summary>
        public static string MyPICCPageNoPiccEnteredText {
            get {
                return ResourceManager.GetString("MyPICCPageNoPiccEnteredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous PICC ähnelt.
        /// </summary>
        public static string MyPICCPagePreviousPICCText {
            get {
                return ResourceManager.GetString("MyPICCPagePreviousPICCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die My PICC ähnelt.
        /// </summary>
        public static string MyPICCPageTitleText {
            get {
                return ResourceManager.GetString("MyPICCPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string PICCDetailPageCancelButtonText {
            get {
                return ResourceManager.GetString("PICCDetailPageCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string PICCDetailPageEditButtonText {
            get {
                return ResourceManager.GetString("PICCDetailPageEditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter an institution ähnelt.
        /// </summary>
        public static string PICCDetailPageInsertCityPlaceholderText {
            get {
                return ResourceManager.GetString("PICCDetailPageInsertCityPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PICC body side: ähnelt.
        /// </summary>
        public static string PICCDetailPagePICCBodysideText {
            get {
                return ResourceManager.GetString("PICCDetailPagePICCBodysideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size in french: ähnelt.
        /// </summary>
        public static string PICCDetailPagePICCFrenchSizeText {
            get {
                return ResourceManager.GetString("PICCDetailPagePICCFrenchSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inserted on: ähnelt.
        /// </summary>
        public static string PICCDetailPagePICCInsertedDateText {
            get {
                return ResourceManager.GetString("PICCDetailPagePICCInsertedDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location: ähnelt.
        /// </summary>
        public static string PICCDetailPagePICCInsertedPlaceText {
            get {
                return ResourceManager.GetString("PICCDetailPagePICCInsertedPlaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Model name: ähnelt.
        /// </summary>
        public static string PICCDetailPagePICCModelNameText {
            get {
                return ResourceManager.GetString("PICCDetailPagePICCModelNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PICC position: ähnelt.
        /// </summary>
        public static string PICCDetailPagePICCPositionText {
            get {
                return ResourceManager.GetString("PICCDetailPagePICCPositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set PICC inactive ähnelt.
        /// </summary>
        public static string PICCDetailPagePICCRemoveButtonText {
            get {
                return ResourceManager.GetString("PICCDetailPagePICCRemoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string PICCDetailPageSaveButtonText {
            get {
                return ResourceManager.GetString("PICCDetailPageSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PICC ähnelt.
        /// </summary>
        public static string PICCDetailPageTitleText {
            get {
                return ResourceManager.GetString("PICCDetailPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Picture detail ähnelt.
        /// </summary>
        public static string PicturePageTitleText {
            get {
                return ResourceManager.GetString("PicturePageTitleText", resourceCulture);
            }
        }
    }
}
